version: '3.8'
services:
  backend:
    build: ./backend
    container_name: study-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - genai
    environment:
      - GENAI_URL=http://genai:8000
    networks:
      - study-net

  genai:
    build: ./genai
    container_name: study-genai
    restart: unless-stopped
    env_file:
      - ./genai/.env
    ports:
      - "8000:8000"
    networks:
      - study-net

  frontend:
    build: ./frontend
    container_name: study-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - study-net

networks:
  study-net:
    driver: bridge 