import { useNavigate } from 'react-router-dom';

export default function AITools() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 transition-colors duration-200">
      <div className="p-8">
        <h1 className="text-4xl font-bold mb-8 text-gray-800 dark:text-white">AI Tools</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div
            onClick={() => navigate('/aitools/chatbot')}
            className="cursor-pointer bg-white dark:bg-gray-800 p-8 rounded-lg shadow-md hover:shadow-lg border border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-600 transition-all duration-200 group"
          >
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mb-3">QA Chatbot</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              Ask any question and get intelligent answers powered by AI. Upload documents and chat with them!
            </p>
            <div className="mt-4 text-blue-600 dark:text-blue-400 font-medium group-hover:underline">
              Start Chatting →
            </div>
          </div>
          
          <div
            onClick={() => navigate('/aitools/quiz')}
            className="cursor-pointer bg-white dark:bg-gray-800 p-8 rounded-lg shadow-md hover:shadow-lg border border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-600 transition-all duration-200 group"
          >
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-white mb-3">AI Quiz</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              Test your knowledge with quizzes generated by AI from your uploaded materials and documents.
            </p>
            <div className="mt-4 text-blue-600 dark:text-blue-400 font-medium group-hover:underline">
              Take Quiz →
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
