import { useNavigate } from 'react-router-dom';

export default function AITools() {
  const navigate = useNavigate();

  return (
    <div className="p-8 dark:text-white min-h-screen bg-gray-100 dark:bg-gray-900">
      <h1 className="text-3xl font-bold mb-6">AI Tools</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div
          onClick={() => navigate('/aitools/chatbot')}
          className="cursor-pointer bg-white dark:bg-gray-800 p-6 rounded shadow hover:bg-blue-50 dark:hover:bg-gray-700 transition"
        >
          <h2 className="text-xl font-semibold">QA Chatbot</h2>
          <p className="text-gray-600 dark:text-gray-300 mt-2">Ask any question and get intelligent answers powered by AI.</p>
        </div>
        <div
          onClick={() => navigate('/aitools/quiz')}
          className="cursor-pointer bg-white dark:bg-gray-800 p-6 rounded shadow hover:bg-blue-50 dark:hover:bg-gray-700 transition"
        >
          <h2 className="text-xl font-semibold">AI Quiz</h2>
          <p className="text-gray-600 dark:text-gray-300 mt-2">Test your knowledge with quizzes generated by AI from your materials.</p>
        </div>
      </div>
    </div>
  );
}
